USE Pratice;
CREATE TABLE STUDENTS(STID INT, SNAME VARCHAR(40), SMAILID VARCHAR(40), COURSEID INT);
INSERT INTO STUDENTS VALUES (101, 'ADAMS', 'add@gmail.com', 10), (102, 'JAMES', 'jay@hotmail.com', 20), (103, 'SCOTT', 'scot@gmail.com', 30);
CREATE TABLE COURSES(COURSESID INT, CNAME VARCHAR(40), CFEE DECIMAL(6,2));
INSERT INTO COURSES VALUES(10, 'SQLSERVER', 1200.00), (20, 'SQL DBA', 1500.00), (40, 'MSBI', 3200.00), (50, 'SAP', 2400.00);

SELECT * FROM STUDENTS;
SELECT * FROM COURSES;
--JOIN 
--A -> ANSI FORMAT JOIN (New Style of join) ===> "ON" keyword Join Condition only 

--A.1 -> INNER JOIN -> Retrive matching condition only
SELECT * FROM STUDENTS INNER JOIN COURSES ON STUDENTS.COURSEID = COURSES.COURSESID;

-- A.2 -> OUTER JOIN
-- A.2.1 -> LEFT OUTER JOIN
SELECT * FROM STUDENTS S LEFT OUTER JOIN COURSES C ON S.COURSEID = C.COURSESID;
-- A.2.1 -> RIGHT OUTER JOIN
SELECT * FROM STUDENTS S RIGHT OUTER JOIN COURSES C ON S.COURSEID = C.COURSESID;
-- A.2.1 -> FULL OUTER JOIN
SELECT * FROM STUDENTS S FULL OUTER JOIN COURSES C ON S.COURSEID = C.COURSESID;

--A.3 -> CROSS JOIN 
SELECT * FROM STUDENTS CROSS JOIN COURSES;
-- A.4 -> NATURAL JOIN  -> Not supported by sql server
-----------------------------------------------
--B. NON - ANSI FORMAT JOIN (Old Style of join) ===> "WHERE" keyword Join Condition only

CREATE TABLE TESTONE(SNO INT, NAME VARCHAR(40));
CREATE TABLE TESTTWO(SNO INT, NAME VARCHAR(40));
INSERT INTO TESTONE VALUES (10,'SAI'), (20,'ADAMS'),(30, 'JAMES'); 
INSERT INTO TESTTWO VALUES (10,'WARNER'), (20,'ALLEN'),(30, 'JONES'); 

SELECT * FROM TESTONE;
SELECT * FROM TESTTWO;

-- B.1 - EQUI JOIN : 
SELECT * FROM TESTONE, TESTTWO WHERE TESTONE.SNO = TESTTWO.SNO;
-- B.2 NON EQUI JOIN : 
SELECT * FROM TESTONE, TESTTWO WHERE TESTONE.SNO > TESTTWO.SNO;
SELECT * FROM TESTONE, TESTTWO WHERE TESTONE.SNO < TESTTWO.SNO;
SELECT * FROM TESTONE, TESTTWO WHERE TESTONE.SNO != TESTTWO.SNO;

--B.3 -- SELF JOIN :
CREATE TABLE EMPDETAIL(EMPID INT, EMPNAME VARCHAR(40), EMPSALARY MONEY, MID INT);
INSERT INTO EMPDETAIL VALUES (101,'SMITH', 8000, 101), (102,'WARNER', 11000, 108), (103,'JAMES', 18000, 109), (104,'SCOTT', 82000, 104), (105,'BALKE', 34000, 110), (106,'ADAMS', 80000, 106);
INSERT INTO EMPDETAIL VALUES (107,'SAM', 8000, 103);
SELECT * FROM EMPDETAIL;
--WHICH IS GET SAME SALARY
--SELECT * FROM EMPDETAIL EONE, EMPDETAIL ETWO WHERE EONE.EMPSALARY = ETWO.EMPSALARY; AND EONE.EMPNAME = 'SMITH';
--SELECT * FROM EMPDETAIL EONE, EMPDETAIL ETWO WHERE EONE.EMPSALARY = ETWO.EMPSALARY AND EONE.EMPNAME = 'SMITH';
SELECT EONE.EMPID, EONE.EMPNAME FROM EMPDETAIL EONE, EMPDETAIL ETWO WHERE EONE.EMPSALARY = ETWO.EMPSALARY AND EONE.EMPNAME = 'SMITH';
