USE Pratice;
--STEP 1: 
CREATE TABLE DEPARTMENT(
DEPTNO INT PRIMARY KEY, DNAME VARCHAR(40), LOCATION VARCHAR(40));

--STEP2 :
INSERT INTO DEPARTMENT VALUES (10, 'DBA', 'HYD'), (20, 'SAP', 'MUMBAI'), (30, 'HR', 'PUNE');

SELECT * FROM DEPARTMENT;

--STEP3 : 
CREATE TABLE EMPLOYEE(
EMPID INT , ENAME VARCHAR(40), SALARY MONEY, DEPTNO INT FOREIGN KEY REFERENCES DEPARTMENT(DEPTNO));

--STEP4 : TEST
INSERT INTO EMPLOYEE VALUES (1, 'Sourav', 90000000000000, 10);
INSERT INTO EMPLOYEE VALUES (2, 'Vicky', 190000000000000, 20);
INSERT INTO EMPLOYEE VALUES (3, 'DEV', 90000000000000, 30);
--These there lines are inserted because the FK(Column value) is same(fk value must be match with pk value) as PK(column value)
--INSERT INTO EMPLOYEE VALUES (4, 'ERROR', 90000000000000, 40); -- give the ereeor bcz vlaues not same FK(Column value) is same as PK(column value)
--40 is DEPTNO but its not exist in the PK column value
SELECT * FROM DEPARTMENT
SELECT * FROM EMPLOYEE