USE Pratice;

--IN Types parameters in STORE PROCEDURE
CREATE TABLE EMPSIn(EID INT, ENAME VARCHAR(20), SALARY MONEY);
INSERT INTO EMPSIn VALUES (101, 'ADAMS', 85000), (102, 'SCOTT', 34000),(103, 'JAMES', 55000), (104, 'WARNER', 12000); 
SELECT * FROM EMPSIn;

CREATE PROCEDURE DemoProcudureForIN(@SPEID INT, @SPENAME VARCHAR(40), @SPSALARY MONEY)
AS BEGIN
INSERT INTO EMPSIn VALUES(@SPEID, @SPENAME, @SPSALARY)
END;

EXEC  DemoProcudureForIn 10, 'raj', 12345


------------------------------------------------------------------------------------------------
CREATE TABLE EMPS(EID INT, ENAME VARCHAR(20), SALARY MONEY);
INSERT INTO EMPS VALUES (101, 'ADAMS', 85000), (102, 'SCOTT', 34000),(103, 'JAMES', 55000), (104, 'WARNER', 12000); 
SELECT * FROM EMPS;

--OUT Types parameters in STORE PROCEDURE
CREATE PROCEDURE DemoProcedure
AS BEGIN 
SELECT * FROM EMPS
END;

EXECUTE DemoProcedure;
--OR
EXEC DemoProcedure;

--OUT STORE PROCEDURE
CREATE PROCEDURE DemoOutProcedure(@EmpsID INT, @EmpsPF INT OUT, @EmpsPT INT OUT)
AS BEGIN
DECLARE @SAL MONEY
SELECT @SAL = SALARY FROM EMPS WHERE EID = @EmpsID
SET @EmpsPF = @SAL * 0.1;
SET @EmpsPT = @SAL * 0.2;
END



DECLARE @EmpsPF INT, @EmpsPT INT
EXECUTE DemoOutProcedure 102, @EmpsPF OUT, @EmpsPT OUT
PRINT 'Provident fund is : ' + CAST(@EmpsPF AS VARCHAR)
PRINT 'Provident tax is : ' + CAST(@EmpsPT AS VARCHAR)