--STORE FUNCTION
------------------------------------SCALAR FUNCTION
CREATE TABLE EMP(EID INT, ENAME VARCHAR(20), SALARY MONEY);
INSERT INTO EMP VALUES (101, 'ADAMS', 85000), (102, 'SCOTT', 34000),(103, 'JAMES', 55000), (104, 'WARNER', 12000); 
SELECT * FROM EMP;
CREATE FUNCTION GrossSalary(@EID INT)
RETURNS MONEY
AS
BEGIN
DECLARE @BASIC MONEY, @HRA MONEY, @DA MONEY, @PF MONEY, @GROSS MONEY
SELECT @BASIC = SALARY FROM EMP WHERE EID = @EID
SET @HRA = @BASIC * 0.1
SET @DA = @BASIC * 0.2
SET @PF = @BASIC * 0.1
SET @HRA = @BASIC * 0.1
SET @GROSS = @BASIC + @HRA + @DA + @PF
RETURN @GROSS
END

SELECT dbo.GrossSalary(101)

--------------------------------------- TABLE FUNCTION
CREATE TABLE EmpTableFuntion(EId INT, EmpName VARCHAR(20), EmpSalary MONEY, EmpDept VARCHAR(40));
INSERT INTO EmpTableFuntion VALUES (101, 'ADAMS', 85000, 'C#'), (102, 'SCOTT', 34000, 'j#'), (103, 'JAMES', 55000, 'C++'), (104, 'WARNER', 12000, 'C#'), (105, 'SC', 3400, 'j#'), (106, 'JAMES G', 55000, '.NET'), (107, 'WARNER G', 12000, 'C#'); 
SELECT * FROM EmpTableFuntion;
--table function create
CREATE FUNCTION SfTableFunction(@DeptName VARCHAR(40))
RETURNS TABLE 
AS
RETURN(SELECT * FROM EmpTableFuntion WHERE EmpDept = @DeptName)
--call
SELECT * FROM SfTableFunction('j#');
