CREATE TABLE BRANCH(BCODE INT, BNAME VARCHAR(30), LOCATION VARCHAR(50));

--TCL
--DML :- can not perform TCL operation because of autocommit is implicit
--INSERT
INSERT INTO BRANCH VALUES (101, 'SBI', 'DELHI');
SELECT * FROM BRANCH;
--TESTING :
BEGIN TRANSACTION 
ROLLBACK
SELECT * FROM BRANCH;

--UPDATE
UPDATE BRANCH SET BCODE = 102 WHERE BCODE = 101;
SELECT * FROM BRANCH;
--TESTING :
BEGIN TRANSACTION 
ROLLBACK
SELECT * FROM BRANCH;

--DELETE
DELETE BRANCH WHERE BCODE = 102;
SELECT * FROM BRANCH;
--TESTING :
BEGIN TRANSACTION 
ROLLBACK
SELECT * FROM BRANCH;
--cant not perfrom rollback due to autocommit
--solution : autocommit change to explict

---TCL
--COMMIT AND ROLLBACK:
BEGIN TRANSACTION
INSERT INTO BRANCH VALUES (101, 'SBI', 'DELHI');
SELECT * FROM BRANCH;
--TESTING : ROLLBACK IS WORK HERE DUE TO AUTOCOMMIT IS EXPLICT
BEGIN TRANSACTION 
ROLLBACK
SELECT * FROM BRANCH;

BEGIN TRANSACTION
INSERT INTO BRANCH VALUES (101, 'SBI', 'DELHI');
COMMIT;
--TESTING : ROLLBACK IS NOT WORK HERE DUE TO AUTOCOMMIT IS EXPLICT BUT WE PERFORM COMMIT OPERATION
BEGIN TRANSACTION 
ROLLBACK
SELECT * FROM BRANCH;

-----------------------------------
TRUNCATE TABLE BRANCH;
SELECT * FROM BRANCH;
-----------------------------------
 
--4.SAVEPOINT :-
INSERT INTO BRANCH VALUES (101, 'SBI', 'DELHI'), (102, 'PNB', 'PUNE'), (103, 'ICICI', 'HYD'), (104, 'BOI', 'CH'), (105, 'YONO', 'ONLINE');
SELECT * FROM BRANCH; 

--HERE EACH STATEMENT IS ROLLBACK 
--BEGIN TRANSACTION 
--DELETE BRANCH WHERE BCODE = 101;
--DELETE BRANCH WHERE BCODE = 103;
--DELETE BRANCH WHERE BCODE = 105;
--SELECT * FROM BRANCH;

--BEGIN TRANSACTION 
--ROLLBACK;
--SELECT * FROM BRANCH;

BEGIN TRANSACTION 
DELETE BRANCH WHERE BCODE = 101;
DELETE BRANCH WHERE BCODE = 103;
SAVE TRANSACTION S1
DELETE BRANCH WHERE BCODE = 105; -- THIS IS ONLY ROLLBACK
SELECT * FROM BRANCH;

BEGIN TRANSACTION 
ROLLBACK TRANSACTION S1;
SELECT * FROM BRANCH;

BEGIN TRANSACTION 
DELETE BRANCH WHERE BCODE = 101;
DELETE BRANCH WHERE BCODE = 103;
SAVE TRANSACTION S1
DELETE BRANCH WHERE BCODE = 105; -- THIS IS ONLY ROLLBACK
COMMIT
SELECT * FROM BRANCH;

BEGIN TRANSACTION 
ROLLBACK ;--TRANSACTION S1;
SELECT * FROM BRANCH;


